//! Generated by capsule
//!
//! `main.rs` is used to define rust lang items and modules.
//! See `entry.rs` for the `main` function.
//! See `error.rs` for the `Error` type.

#![no_std]
#![no_main]
#![feature(lang_items)]
#![feature(alloc_error_handler)]
#![feature(panic_info_message)]

// define modules
mod blake2b;
mod constant;
mod entry;
mod error;

use ckb_combine_lock_common::logger;
use ckb_std::default_alloc;
use log::warn;

ckb_std::entry!(program_entry);
default_alloc!();

/// program entry
///
///  Both `argc` and `argv` can be omitted.
fn program_entry() -> i8 {
    drop(logger::init());
    // Call main function and return error code
    match entry::main() {
        Ok(_) => 0,
        Err(err) => {
            warn!("script exit with error: {:?}", err);
            err as i8
        }
    }
}
